services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: ${APP_ENV_FILE:-.env.prod}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: unless-stopped
    command:
      - start
    env_file: ${APP_ENV_FILE:-.env.prod}
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak.localys.shop
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
    depends_on:
      - db

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ${APP_ENV_FILE:-.env.prod}
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OIDC_ISSUER_URI: https://keycloak.localys.shop/realms/localys-realm
      APP_MEDIA_UPLOAD_DIR: /app/uploads
    volumes:
      - media_uploads:/app/uploads
      - /opt/localys/localys-marketplace/uploads:/app/uploads
    depends_on:
      - db
      - keycloak

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - /opt/localys/localys-marketplace/uploads:/var/www/uploads:ro
    depends_on:
      - frontend
      - backend
      - keycloak

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  dbdata:
  media_uploads:
