spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: apppass

  application:
    name: localys-marketplace
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:https://keycloak.localys.shop/realms/localys-realm}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

app:
  media:
    upload-dir: uploads
