spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: apppass

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/phase1-realm
